### ISSUE TITLE
Exchange 是基于旧 Exchange 的值创建的新的 Enum 类型对象，我在 database 的 load_bar_data 的时候，无法进行类型转化。

### ISSUE THREAD

**Issue by poloxue** [veighna-global/vnpy_crypto#27]
vnpy_crypto 的 Exchange 是基于旧 Exchange 的值创建的新的 Enum 类型对象，我在 database 的 load_bar_data 的时候，里面用的 vnpy.trader.constant 的 Exchange，无法进行 crypto 交易所的类型转化。

错误提示：

```bash
Traceback (most recent call last):
  File "/vnpy/examples/candle_chart/run.py", line 15, in <module>
    bars = database.load_bar_data('BTC-USDT-SWAP',
  File "/virtualenv/vnpy/lib/python3.9/site-packages/vnpy_sqlite/sqlite_database.py", line 288, in load_bar_data
    exchange=Exchange(db_bar.exchange),
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'OKX' is not a valid Exchange
```

好像是 Python 的 enum 的作者另外还扩展了一个包 aenum，能直接扩展原始的 Enum 类型。我通过以下的代码，直接把 Exchange 修改后就没问题了。

```python
from aenum import extend_enum

from vnpy.trader.constant import Exchange


# Add crypto currency exchanges
exchange_names = [
    "BINANCE",
    "BITFINEX",
    "BITSTAMP",
    "BYBIT",
    "COINBASE",
    "DERIBIT",
    "DYDX",
    "FTX",
    "GATEIO",
    "HUOBI",
    "OKX"
]

# Generate new enum class

[extend_enum(Exchange, exchange_name, exchange_name) for exchange_name in exchange_names]
```

这个包我没有详细看，不知道有没有其他问题。

**Comment by poloxue** [comment]
看到了，需要手动 init 函数将原来的 Exchange 替换。
